version: '3'
services:
  panda-eureka:
    build:
      context: ./
      dockerfile: ./panda-eureka/Dockerfile
    restart: always
    container_name: panda-eureka
    image: panda-eureka
    ports:
     - 8761:8761

  panda-config:
    build:
      context: ./
      dockerfile: ./panda-config/Dockerfile
    restart: always
    container_name: panda-config
    image: panda-config
    links:
     - panda-eureka:panda-eureka
    depends_on:
     - "panda-eureka"
    ports:
     - 8888:8888
  panda-monitor:
    build:
      context: ./
      dockerfile: ./panda-visual/panda-monitor/Dockerfile
    restart: always
    image: panda-monitor
    container_name: panda-monitor
    links:
     - panda-eureka:panda-eureka
    depends_on:
     - "panda-eureka"
     - "panda-config"
    ports:
     - 9999:9999
